<x-filament-panels::page.simple>
    @include('filament.partials.login-panel-left')
    <div class="hr-login-heading">Portal HR Unijaya</div>
    <p class="hr-login-sub mb-6">Masuk dengan akaun anda</p>

    <x-filament-panels::form id="form" wire:submit="authenticate">
        {{ $this->form }}
        <x-filament-panels::form.actions
            :actions="$this->getCachedFormActions()"
            :full-width="$this->hasFullWidthFormActions()"
        />
    </x-filament-panels::form>

    @if(config('services.google.client_id'))
        <div class="relative my-6">
            <div class="absolute inset-0 flex items-center">
                <span class="w-full border-t" style="border-color:#e5e7eb;"></span>
            </div>
            <div class="relative flex justify-center text-xs">
                <span class="px-2 bg-white text-gray-500">atau</span>
            </div>
        </div>
        <a href="{{ route('auth.google') }}"
           class="flex w-full items-center justify-center gap-3 rounded-lg border px-4 py-2.5 text-sm font-medium transition hover:opacity-80"
           style="border-color:#e5e7eb;color:#374151;">
            <svg class="h-4 w-4" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"/>
                <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/>
                <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05"/>
                <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/>
            </svg>
            Daftar masuk dengan Google
        </a>
    @endif

    {{-- Credentials modal button --}}
    <div style="margin-top: 2rem; text-align: center;">
        <button
            type="button"
            onclick="document.getElementById('credentialsModal').style.display='block';"
            style="padding: 0.5rem 1rem; background: #f0f9ff; color: #1e40af; border: 1px solid #bfdbfe; border-radius: 0.375rem; cursor: pointer; font-weight: 500; font-size: 0.875rem;">
            📋 View Demo Users & Credentials
        </button>
    </div>

    {{-- Credentials Modal --}}
    <div id="credentialsModal" style="display:none; position:fixed; z-index:9999; left:0; top:0; width:100%; height:100%; background-color:rgba(0,0,0,0.5);">
        <div style="background-color:#fff; margin:5% auto; padding:2rem; border-radius:0.5rem; width:90%; max-width:900px; max-height:80vh; overflow-y:auto; box-shadow:0 4px 6px rgba(0,0,0,0.1);">
            <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:1.5rem;">
                <h2 style="margin:0; font-size:1.5rem; color:#061B31;">Demo Credentials (All Staff)</h2>
                <button onclick="document.getElementById('credentialsModal').style.display='none';" style="background:none; border:none; font-size:1.5rem; cursor:pointer; color:#666;">✕</button>
            </div>

            <p style="margin-bottom:1.5rem; color:#666; font-size:0.875rem;">
                <strong>Password for all users:</strong> <code style="background:#f0f9ff; padding:0.25rem 0.5rem; border-radius:0.25rem;">password123</code><br>
                Click any name or email to auto-fill both login and password, then sign in.
            </p>

            <table style="width:100%; border-collapse:collapse; font-size:0.85rem;">
                <thead>
                    <tr style="background:#f3f4f6; border-bottom:2px solid #e5e7eb;">
                        <th style="padding:0.75rem; text-align:left; color:#1f2937; font-weight:600;">Name</th>
                        <th style="padding:0.75rem; text-align:left; color:#1f2937; font-weight:600;">Email</th>
                        <th style="padding:0.75rem; text-align:left; color:#1f2937; font-weight:600;">Role</th>
                    </tr>
                </thead>
                <tbody>
                    <tr style="border-bottom:1px solid #e5e7eb;"><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='shahril.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline; padding:0;">Shahrilnizam Mohamad</button></td><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='shahril.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline;">shahril.unijaya@gmail.com</button></td><td style="padding:0.75rem;"><span style="background:#dbeafe; color:#1e40af; padding:0.25rem 0.75rem; border-radius:0.25rem; font-size:0.75rem; font-weight:600;">Admin</span></td></tr>
                    <tr style="border-bottom:1px solid #e5e7eb;"><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='haryati.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline; padding:0;">Haryati Binti Moktar</button></td><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='haryati.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline;">haryati.unijaya@gmail.com</button></td><td style="padding:0.75rem;"><span style="background:#dcfce7; color:#15803d; padding:0.25rem 0.75rem; border-radius:0.25rem; font-size:0.75rem; font-weight:600;">Manager</span></td></tr>
                    <tr style="border-bottom:1px solid #e5e7eb;"><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='hakime.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline; padding:0;">Mohd Hakime Bin Md Nasri</button></td><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='hakime.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline;">hakime.unijaya@gmail.com</button></td><td style="padding:0.75rem;"><span style="background:#dcfce7; color:#15803d; padding:0.25rem 0.75rem; border-radius:0.25rem; font-size:0.75rem; font-weight:600;">Manager</span></td></tr>
                    <tr style="border-bottom:1px solid #e5e7eb;"><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='kussairi.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline; padding:0;">Ahmad Kussairi Bin Sutikno</button></td><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='kussairi.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline;">kussairi.unijaya@gmail.com</button></td><td style="padding:0.75rem;"><span style="background:#dcfce7; color:#15803d; padding:0.25rem 0.75rem; border-radius:0.25rem; font-size:0.75rem; font-weight:600;">Manager</span></td></tr>
                    <tr style="border-bottom:1px solid #e5e7eb;"><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='anis.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline; padding:0;">Anis Eliyani Binti Mohd Ubaidiy</button></td><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='anis.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline;">anis.unijaya@gmail.com</button></td><td style="padding:0.75rem;"><span style="background:#dbeafe; color:#1e40af; padding:0.25rem 0.75rem; border-radius:0.25rem; font-size:0.75rem; font-weight:600;">HR</span></td></tr>
                    <tr style="border-bottom:1px solid #e5e7eb;"><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='suandy.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline; padding:0;">Suandy Shamsudin</button></td><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='suandy.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline;">suandy.unijaya@gmail.com</button></td><td style="padding:0.75rem;"><span style="background:#fef2f2; color:#dc2626; padding:0.25rem 0.75rem; border-radius:0.25rem; font-size:0.75rem; font-weight:600;">Staff</span></td></tr>
                    <tr style="border-bottom:1px solid #e5e7eb;"><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='syafiqazwan.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline; padding:0;">Mohamad Syafiq Azwan Bin Mustafa</button></td><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='syafiqazwan.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline;">syafiqazwan.unijaya@gmail.com</button></td><td style="padding:0.75rem;"><span style="background:#fef2f2; color:#dc2626; padding:0.25rem 0.75rem; border-radius:0.25rem; font-size:0.75rem; font-weight:600;">Staff</span></td></tr>
                    <tr style="border-bottom:1px solid #e5e7eb;"><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='rubmin.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline; padding:0;">Muhamad Rubmin Bin Muhamad</button></td><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='rubmin.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline;">rubmin.unijaya@gmail.com</button></td><td style="padding:0.75rem;"><span style="background:#fef2f2; color:#dc2626; padding:0.25rem 0.75rem; border-radius:0.25rem; font-size:0.75rem; font-weight:600;">Staff</span></td></tr>
                    <tr style="border-bottom:1px solid #e5e7eb;"><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='hafiz.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline; padding:0;">Muhammad Hafiz Ruslan</button></td><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='hafiz.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline;">hafiz.unijaya@gmail.com</button></td><td style="padding:0.75rem;"><span style="background:#fef2f2; color:#dc2626; padding:0.25rem 0.75rem; border-radius:0.25rem; font-size:0.75rem; font-weight:600;">Staff</span></td></tr>
                    <tr style="border-bottom:1px solid #e5e7eb;"><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='nurin.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline; padding:0;">Nurin Saffa Binti Safuan</button></td><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='nurin.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline;">nurin.unijaya@gmail.com</button></td><td style="padding:0.75rem;"><span style="background:#fef2f2; color:#dc2626; padding:0.25rem 0.75rem; border-radius:0.25rem; font-size:0.75rem; font-weight:600;">Staff</span></td></tr>
                    <tr style="border-bottom:1px solid #e5e7eb;"><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='anasuha.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline; padding:0;">Anasuha Binti Mohd Ali</button></td><td style="padding:0.75rem;"><button type="button" onclick="document.querySelector('input[name=\'email\']').value='anasuha.unijaya@gmail.com'; document.querySelector('input[name=\'password\']').value='password123'; document.getElementById('credentialsModal').style.display='none'; document.querySelector('input[name=\'email\']').focus();" style="background:none; border:none; color:#1e40af; cursor:pointer; text-decoration:underline;">anasuha.unijaya@gmail.com</button></td><td style="padding:0.75rem;"><span style="background:#fef2f2; color:#dc2626; padding:0.25rem 0.75rem; border-radius:0.25rem; font-size:0.75rem; font-weight:600;">Staff</span></td></tr>
                    <tr style="border-bottom:1px solid #e5e7eb;"><td colspan="3" style="padding:1rem; background:#f9fafb; text-align:center; color:#666; font-size:0.875rem;"><em>+ 24 more staff (see storage/app/seed-credentials.csv for complete list)</em></td></tr>
                </tbody>
            </table>
        </div>
    </div>

    <p class="hr-login-footer">© 2026 Unijaya Resources Sdn Bhd</p>
</x-filament-panels::page.simple>
